stages: 
    - build
    - test
    - deploy staging
    - deploy production


build website: 
    stage: build
    image: node:18-alpine
    script:
        - yarn install
        - yarn lint
        - yarn test
        - yarn build
    artifacts:
        paths: 
            - build  #keep the artifact because it will be used in another stage
            
# Testing the website
test website:
    image: node:18-alpine
    stage: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"


.deploy:
    image:
        name: amazon/aws-cli:2.11.6
        entrypoint: [""]
    script: 
        - aws --version
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete   # delete any objects in bucket if exist
        - curl $CI_ENVIRONMENT_URL | grep "React App"

################### Deploy the App in 2 Environments #######################
deploy to staging:
    stage: deploy staging
    environment: staging
    extends: .deploy   # use the .deploy section here


deploy to production:
    stage: deploy production
    environment: production
    extends: .deploy   # use the .deploy section here




